### ISSUE TITLE
Get the associated `char` of a `GlyphId` ?

### ISSUE THREAD

**Issue by intjelic** [alexheretic/ab-glyph#18]
I can query the glyph ID from a `char` but how to do the opposite?

The use case is to make a list of `char` available in the font. To do that, I'm able to get the number of glyph with `glyph_count()`. It says "Glyph identifiers for this font will always be in the range 0..self.glyph_count()", therefore I understand that all the glyphs are from 0 to this number. But then I don't know how to retrieve the `char` associated to each glyph ID.

Also, I'm not sure if all glyph has an associated char. I think it does, but I can't be sure.

---

By the way, I prefer `ab_glyph` interface over `rusttype`, however, for developers who don't have a strong background in font-related stuff, it's a bit cryptic. Stuff like 'side bearing', `kern`, `advance`, `ascent`, `descent`,  I was able to figure out the meaning of some but not all of them. Do you have a link where I could get those infos ? For instance, even the description of the `draw()` message is unclear, at least to me: "[...] with a coverage value in the range [0.0, 1.0].". It took me time to understand it was the amount of gray color. But that's just my opinion, I may be lacking in the literature.

**Comment by alexheretic** [comment]
When it comes to new functionality, like glyph_id -> char there are probably two main things to consider
* How would it be done using _ttf-parser_ directly?
* Should the functionality be provided by _ab_glyph_?

_ab_glyph_ isn't intended to supply everything in _ttf-parser_, so I'd start with using _ttf-parser_ alongside then proposing the addition to this crate if that makes sense.

_ab_glyph_ doesn't expose _ttf-parser_ internals intentionally but you can just build a new `Face` from the font data.
```rust
let font = ab_glyph::FontRef::try_from_slice(EXO2)?;
let ttfp_face = ttf_parser::Face::from_slice(EXO2, 0)?;
```

> it's a bit cryptic

Yes that's my personal experience with font stuff too. PRs to improve the docs are very welcome! [This answer provides some info on ascent/descent](https://github.com/alexheretic/ab-glyph/issues/6#issuecomment-638728760) I'm not sure we can put images in the docs yet. Maybe ascii?

But the coverage value _isn't_ "amount of gray color", drawing does not support any color. It just returns how much the glyph covered a particular pixel. Let's improve this one, let me know your thoughts: #19

**Comment by JAicewizard** [comment]
ttf_parser now allows for reading all codepoints from a font. This way you can build up a table matching codepoint to glyphID (and thus vise-versa).
This should at least work, although not very performant for large fonts.

**Comment by robinkrahl** [comment]
I stumbled over this issue because iterating over all characters and getting their glyph IDs used to work fine in `rusttype` 0.8 (with `stb_truetype`) but is terribly slow with `rusttype` 0.9 and `ab_glyph` (with `ttf-parser`; ~ factor 5 in release mode, much worse in debug mode).  (I thought I had created an infinite loop when refactoring from `rustttype` 0.8 to 0.9, but no, it’s just really, really slow!)  Consider this benchmark:

```test
running 4 tests
test stb_truetype          ... bench:   4,600,619 ns/iter (+/- 8,141)
test ttf_parser            ... bench:  23,700,239 ns/iter (+/- 137,010)
test ttf_parser_codepoints ... bench:      58,589 ns/iter (+/- 259)
test ttf_parser_subtable   ... bench:   9,930,148 ns/iter (+/- 813,532)
```

```rust
#![cfg(test)]
#![feature(test)]

extern crate test;

const DATA: &[u8] = include_bytes!("/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf");
const COUNT: usize = 668;

#[bench]
fn stb_truetype(b: &mut test::Bencher) {
    let font = stb_truetype::FontInfo::new(DATA, 0).unwrap();
    b.iter(|| {
        let mut count = 0;
        for c in char::default()..std::char::MAX {
            if font.find_glyph_index(u32::from(c)) > 0 {
                count += 1;
            }
        }
        assert_eq!(count, COUNT);
    });
}

#[bench]
fn ttf_parser(b: &mut test::Bencher) {
    let font = ttf_parser::Face::from_slice(DATA, 0).unwrap();
    b.iter(|| {
        let mut count = 0;
        for c in char::default()..std::char::MAX {
            if font.glyph_index(c).map(|gid| gid.0 > 0).unwrap_or(false) {
                count += 1;
            }
        }
        assert_eq!(count, COUNT);
    });
}

#[bench]
fn ttf_parser_subtable(b: &mut test::Bencher) {
    let font = ttf_parser::Face::from_slice(DATA, 0).unwrap();
    let subtables: Vec<_> = font.character_mapping_subtables().filter(|s| s.is_unicode()).collect();
    b.iter(|| {
        let mut count = 0;
        for c in char::default()..std::char::MAX {
            if subtables.iter().filter_map(|s| s.glyph_index(u32::from(c))).any(|gid| gid.0 > 0) {
                count += 1;
            }
        }
        assert_eq!(count, COUNT);
    });
}

#[bench]
fn ttf_parser_codepoints(b: &mut test::Bencher) {
    let font = ttf_parser::Face::from_slice(DATA, 0).unwrap();
    let subtables: Vec<_> = font.character_mapping_subtables().filter(|s| s.is_unicode()).collect();
    b.iter(|| {
        let mut chars = std::collections::HashSet::new();
        for subtable in &subtables {
            subtable.codepoints(|c| {
                use std::convert::TryFrom as _;

                if let Ok(ch) = char::try_from(c) {
                    let idx = subtable.glyph_index(c);
                    if idx.map(|gid| gid.0 > 0).unwrap_or(false) {
                        chars.insert(ch);
                    }
                }
            })
        }
        assert_eq!(chars.len(), COUNT);
    });
}
```

You have to decide whether you want to add a wrapper for the `codetables` approach to `ab_glyph`, but I wanted to leave this here in any case for everyone with the same problem.

**Comment by alexheretic** [comment]
Thanks, I think that `ttf_parser_codepoints` example points us towards how this can be done with _ttf-parser_.

> Should the functionality be provided by ab_glyph?

This isn't core functionality of _ab_glyph_, which means I don't 100% understand the use case myself. But it is quite related to the concepts _ab_glyph_ does already expose (`char` -> `GlyphId`). So perhaps we should expose a lightweight method for this.

Would a method where you could iterate through distinct `(char, GlyphId)` pairs suffice?
```rust
struct ExampleFont<'a> {
    face: &'a ttf_parser::Face<'a>,
}


impl<'a> ExampleFont<'a> {
    fn codepoints(&self) -> impl Iterator<Item = (char, ab_glyph::GlyphId)> + 'a { ... }
}
```
```rust
for (ch, glyph_id) in font.codepoints().sorted_by_key(|&(_, gid)| gid).take(20) {
    eprintln!("{}: {:?}", glyph_id.0, ch);
}
```
```
1: ' '
2: '0'
3: '1'
4: '2'
5: '3'
6: '4'
7: '5'
8: '6'
9: '7'
10: '8'
11: '9'
12: 'A'
13: 'B'
14: 'C'
15: 'D'
16: 'E'
17: 'F'
18: 'G'
19: 'H'
20: 'I'
```

**Comment by robinkrahl** [comment]
> I don't 100% understand the use case myself

To add some context:  [`printpdf`](https://lib.rs/crates/printpdf) needs to build a character map when embedding fonts into a PDF document.  Currently, it uses `rusttype` 0.8 and iterates over `0x0000..0xffff`.  I tested upgrading to 0.9 or using `ab_glyph`.  In the meantime, I realized it might be sufficient to use `ttf-parser` directly for this usecase because `printpdf` only has to access the unscaled glyph metrics.  So I won’t be mad if you consider this feature out of scope for `ab_glyph`.  That being said, an API for easier access to the codepoints would definetely be useful, either in this crate or in `ttf-parser`.

> Would a method where you could iterate through distinct `(char, GlyphId)` pairs suffice?

Yes, I think that would be a good interface.

**Comment by JAicewizard** [comment]
I would absolutely love this, but in the original discussion for `ttf_parser` it was brought up that there could be duplicate characters with different glyphids in different tables. This is some kind of undefined behavior in ttf/otf fonts I think, so it would need to be decided whether or not to filter out duplicates, or something else.
This is where I kind of disagree with the `ttf_parser` implementation because it separated the tables and requires you to get the glyphID yourself after the fact, while the glyphID is literally up for grabs when iterating over the codepoints. This does mean that you always get a correct mapping from char->glyphID, but it lowers performance because you basically always need the glyphID so why not provide it.

@robinkrahl The way I did it by basically just doing the same as you did in your bench. I tried to advocate for an easier API as well but it didn't work.

**Comment by alexheretic** [comment]
Let me know what you guys think of #24. Does the naming make sense, does it help?

**Comment by JAicewizard** [comment]
Yeah the naming makes sense to me. I would switch the tuple order around because the `char` is the main object and `id` is just a property related to the `char` but that is just nitpicking.

**Comment by alexheretic** [comment]
> I would switch the tuple order around because the `char` is the main object and `id` is just a property related to the `char`

Yeah I had it that way to start with. I'm not 100% but it seemed nice to have `(GlyphId, char)` to make it easy to collect into a lookup map _(since `char` -> `GlyphId` lookup is already provided by `Font::glyph_id`)_.
```rust
let map: HashMap<_, _> = font.codepoint_ids().collect();
assert_eq!(map.get(&GlyphId(75)), Some(&'!'));
```
